spring:
  datasource:
    driver-class-name: ENC(AMoa7WhSHr/ctIiAkkLQ03TSD69yoN48zLtf0CceMqE5xvWXzE0m5Q==)
    url: ENC(uNp1I04XLkeakxRobS89LQ5Jimfc8a+9EmdG6wv2U6CbPRnD93eE+8P1XoWqXAPvrzXNBgh0/vg=)
    username: ENC(IShacdOKlJ30vTGX8172PM0nkvr4pzMu)
    password: ENC(PSuKHqKzQVhsx9KV5Bs/7266gSHDz7Mh)
    hikari:
      maximumpoolsize: 150
      connectionTimeout : 30000
      maxLifetime : 1800000
      minimum-idle: 10